export { default as Header } from './Header/Header';
export { default as Hero } from './Hero/Hero';
export { default as Payments } from './Payments/Payments';
export { default as DocumentedApis } from './DocumentedApis/DocumentedApis';
export { default as FraudDetection } from './FraudDetection/FraudDetection';
export { default as TrustedBusinesses } from './TrustedBusinesses/TrustedBusinesses';
export { default as PoweringGrowth } from './PoweringGrowth/PoweringGrowth';
export { default as BackedPartners } from './BackedPartners/BackedPartners';
export { default as AcceptingPayments } from './AcceptingPayments/AcceptingPayments';